name: new_pokemon_app
description: PokeApp
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.0
  dio: ^4.0.6
  hive_flutter: ^1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.6
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true